### ISSUE TITLE
Compatibility issue with bluetooth

### ISSUE THREAD

**Issue by vicus85** [pimoroni/pxt-scrollbit#2]
Scroll:bit package seems to be incompatible with Bluetooth services. Whenever both are used, micro:bit will show a sad face and "0"/"2". Any idea why?

**Comment by microbit-mark** [comment]
@Gadgetoid can you answer this one? I don't yet have a scroll:bit to recreate this with.

**Comment by Gadgetoid** [comment]
It's an out-of-memory error as far as I'm aware- not so much a bug, but a resource limitation. I don't believe there's a fix- since Bluetooth is inherently memory hungry. and scroll:bit requires an in-memory buffer for the display.

@microbit-mark Is there any way to flag these incompatibilities so that users don't try to mix and match packages that wont play nice together?

**Comment by Gadgetoid** [comment]
@vicus85 this might be fixed in v0.0.5 when #5 is merged.

I believe the issue was in using ~1024bytes for a gamma correction curve leaving no headroom for Bluetooth. I've now moved this feature into C where I can better control the data type.

I can run Bluetooth alongside Scroll:bit- but I can't seem to get Bluetooth to do anything useful. I'm not sure if this is because I don't have the right setup, or because Bluetooth is still running into issues and failing.

**Comment by microbit-mark** [comment]
Sounds like this may no longer be a problem, but you can flag incompatibilities eg <img width="765" alt="screenshot 2019-01-28 at 12 50 37" src="https://user-images.githubusercontent.com/31242877/51837482-68173d80-22fb-11e9-9655-8cc9a608d7d3.png"> but nnot sure how this is done. Maybe chekc with @abchatra

**Comment by abchatra** [comment]
Take a look at this https://github.com/Microsoft/pxt-neopixel/blob/master/pxt.json
Need to specify something like in the config
    "yotta": {
        "config": {
            "microbit-dal": {
                "bluetooth": {
                    "enabled": 0
                }
            }
        }
    },
