### ISSUE TITLE
display icon block does not work without display your changes block

### ISSUE THREAD

**Issue by nielsswinkels** [pimoroni/pxt-scrollbit#8]
It is unclear (or a bug?) that the block "display icon _ at col _ row _ with brightness_" does not do anything unless you add a block "display your changes" afterwards. 

If it is supposed to be this way, the block maybe shouldnt have the word display in the name?

![20190529_144211](https://user-images.githubusercontent.com/5718354/58558193-754c2680-8220-11e9-99e3-c40354a7080b.jpg)

**Comment by Gadgetoid** [comment]
We looked into renaming blocks to clarify their intent- since it's definitely confusing to have a block read "display X" when it really means "draw X to buffer". Unfortunately we can't roll out any name changes or dramatic changes to this library because it will break out printed educational documentation.

On the other side of the coin, I'm apprehensive to change the behaviour of the library to automatically call "display your changes" because this can make doing anything involving setting single pixels extremely slow, and it doesn't make sense to have "display icon" show immediately, while "set pixel" does not. Complicated!

What we can do, however, is expand the built-in documentation to better explain this (admittedly weird) behaviour to users. The docstrings above each block definition are rendered a tooltips in the Makecode editor. Elaborating upon these should help with understanding. I've opened #14 to track this.
